Feature/int 44
NaYeongSeokGame/ImNayeoungSeokToo-client pull request #42
Opened 2023-07-22 11:31 UTC by uaej

## Jira Issue 번호
#44

## 작업 내용
- 전체 목록 보여주는 페이지를 추가했습니다. 
- 아직 검색 기능 및 무한 스크롤 기능은 제대로 동작하지 않는 상태라 추후에 브랜치 더 파서 작업하도록 하겠습니다. 

## Checklist

- [ ] Code Review 요청
- [ ] PR 제목 commit convention에 맞는지 확인
- [ ] Label 설정
- [ ] Jira 코드 리뷰 상태로 변경

2023-07-22 14:43 UTC, Forourhappy reviewed
카드 컴포넌트랑 페이지 만드시느라 고생 많으셨어요!
저희 디스코드에서 이야기했던 것처럼 px을 rem으로 바꿔주시면 좋을 것 같아요.

2023-07-23 12:32 UTC, RookieAND requested changes
수정할 사항이 몇 개 보여 리뷰를 달아두었습니다.
금주 작업해주셔서 고생 많으셨어요 메이.

2023-07-23 12:32 UTC, RookieAND commented on src/components/pages/QuizSearch/QuizSearch.style.tsx
> +export const QuizPresetCard= styled.div`
이런 건 굳이 template literal 내에 theme을 매개변수로 받는 함수를 반환하지 않아도 될 거 같아요.

```ts
const QuizPresetCard = styled.div`
    margin-bottom: 1rem;
`
```ts

2023-07-23 12:32 UTC, RookieAND commented on src/components/pages/QuizSearch/QuizSearch.style.tsx
> +export const SearchQuizWrapper = styled.div`
요것도 마찬가지로 template literal 내에 theme을 매개변수로 받는 함수를 반환하지 않아도 될 거 같아요.

const SearchQuizWrapper= styled.div`
    padding: 1rem;
`
```ts

2023-07-23 12:32 UTC, RookieAND commented on src/components/pages/QuizSearch/QuizSearch.tsx
> +  const limit = 6;
이런 상수는 컴포넌트 밖으로 빼도 될 거 같아요.

2023-07-23 12:32 UTC, RookieAND commented on src/components/pages/QuizSearch/QuizSearch.tsx
> +    const observer = new IntersectionObserver(
추후에 IntersectionObserver를 사용하는 로직을 커스텀 훅으로 추상화 해보는 건 어떨까요?

2023-07-23 12:32 UTC, RookieAND commented on src/main.tsx
> +import QuizSearch from './components/pages/QuizSearch';
절대 경로 `@` 로 변경 부탁드립니다.

2023-07-24 01:51 UTC, shinpanda commented on src/components/main/PresetCard/PresetCard.style.ts
> +      // padding: 0.1rem 0.75rem;
요 padding 은 사용하지 않으시는 거라면 정리하면 좋을 것 같아요

2023-07-24 01:51 UTC, shinpanda commented on src/styles/fonts.ts
>      lineHeight: `${LINE_HEIGHT_RATIO * 60}px`,
lineHeight도 px로 되어 있어서 같이 rem 단위로 고쳐지면 좋을 것 같습니당

2023-07-24 09:18 UTC, uaej commented on src/styles/fonts.ts
>      lineHeight: `${LINE_HEIGHT_RATIO * 60}px`,
이 부분은 제가 다음 브랜치에서 또 수정하는 부분이 있어서 해당 부분 반영할때 같이 넣겠습니다!

2023-07-24 09:19 UTC, uaej commented
판다 외에 코멘트 달아주신 부분들은 모두 수정완료했습니다. 
반영이 좀 늦었는데, 다들 리뷰해주셔서 감사드립니다!

2023-07-24 13:19 UTC, merged