[INT-51] 퀴즈 풀이 페이지 퍼블리싱
NaYeongSeokGame/ImNayeoungSeokToo-client pull request #44
Opened 2023-07-23 17:37 UTC by Forourhappy

## Github Issue 번호
#51 #53
## 작업 내용
- 퀴즈 풀이 페이지 퍼블리싱
## 논의하고 싶은 점
- progress bar를 만들었는데, 시간이 지날 때마다 차는 형태라 조금 끊기는 감이 있어서 이 부분은 논의해 보면 좋을 것 같아요.
- 시계 이미지 안에 카운트다운이 되도록 디자인이 되어 있는데, 실질적으로 구현하다 보니, 카운트가 2자리 일 때, 처리가 난감하기도 했고, rotate 처리 하다 보니까 크기나 margin이 안 맞는 부분이 있는 것 같아요.
그리고 저희가 PWA 형태다 보니까 시계 위치를 잡기가 어렵더라고요. 이 부분은 현재 translateX로 처리해주긴 했는데, 더 좋은 방법이 있다면 공유해주시면 감사하겠습니다.
## Checklist

- [x] Code Review 요청
- [x] PR 제목 commit convention에 맞는지 확인
- [x] Label 설정
- [x] Jira 코드 리뷰 상태로 변경

2023-07-24 01:45 UTC, RookieAND requested changes
고생하셨습니다 포.
작업 관련하여 의논할 점을 기술해두었습니다.

2023-07-24 01:45 UTC, RookieAND commented on src/components/pages/QuizPlay/QuizPlay.style.ts
> +export const QuizTimerImage = styled.div`
이미지 자체의 width, height 값을 꼭 하드하게 넣어야 할까요?
만약 그게 아니라면 img 태그로 해결해봐도 좋을 것 같아요.

또한 absolute 기반의 포지셔닝이 아니라 다른 방식으로 요소를 배치하는 법을 사용해보는 것은 좀 어려울까요? Grid도 대안이 될 수 있어보여요.

2023-07-24 01:45 UTC, RookieAND commented on src/components/pages/QuizPlay/QuizPlay.style.ts
> +      border: 10px solid ${colors.white};
요기도 rem으로 수정 부탁드립니다.

2023-07-24 01:45 UTC, RookieAND commented on src/components/pages/QuizPlay/QuizPlay.tsx
> +        value={timeToSolveQuiz - leftSecond}
이 부분은 결국 useTimer에서 반환된 값이 1초를 기준으로 돌아가기 때문에 생긴 문제라고 생각해요.

useTimer의 interval 주기를 줄이거나, requestAnimationFrame을 사용해서 아직 잔여 시간이 남았다면 frame 마다 알맞은 시간을 감산시킨 값 (16ms 씩 소거) 를 제거하는 방식은 어떤가요?

2023-07-24 01:45 UTC, RookieAND commented on src/components/pages/QuizPlay/QuizPlay.style.ts
> +  color: #db0000;
이 부분은 HEX 값을 무조건 넣어야 했나요? 테마 컬러 토큰에 포함된 값인지 체크해보고, 아니라면 디자인을 수정하는게 맞아보여요

2023-07-24 11:33 UTC, uaej approved these changes
포 고생하셨어요! 
제가 실행을 안해봐서 어떻게 끊기는지는 모르겠으나, 아래 링크처럼 프로그래스 바에 애니메이션을 추가해주면 스무스하게 동작할 수 있을거같아요! 
https://codepen.io/evawythien/pen/jegRxN

2023-07-24 11:33 UTC, uaej commented on src/components/pages/QuizPlay/QuizPlay.style.ts
> +  color: #db0000;
이 부분은 타이머 숫자 표시할때 쓰는 빨간색이라서 테마 컬러토큰에 없는게 맞아요! 추가로 colors 파일에 추가해주는게 좋을거같네요.

2023-07-24 12:50 UTC, Forourhappy commented on src/components/pages/QuizPlay/QuizPlay.style.ts
> +export const QuizTimerImage = styled.div`
저는 정확하게 명시된 디자인이 있다면 철저하게 그것에 맞춰 주어야 한다는 생각이라서 빡빡하게 값을 맞추긴 했습니다.
뒤에 img 태그로 해결 본다는 건 어떤 의민지 조금 더 자세하게 설명 가능할까요?

그리고 마지막 부분은 relative div를 감싸니까 포지션은 쉽게 잡았습니다.
Grid가 있다는 게 방금 떠올랐어요. ㅋㅋㅋㅋ 
그런데 저는 Grid가 익숙지 않아서 그런지 레이아웃 잡기 좀 난해해 보여요. 아무래도 크기도 제각각이고 디자인이 박스로 둘러 싸여진 형태가 아니라서 정확한 위치를 잡기에는 absolute로 처리하는 편이 더 간편할 것 같았습니다.

2023-07-24 12:50 UTC, Forourhappy commented on src/components/pages/QuizPlay/QuizPlay.style.ts
> +      border: 10px solid ${colors.white};
예압!

2023-07-24 13:08 UTC, Forourhappy commented on src/components/pages/QuizPlay/QuizPlay.tsx
> +        value={timeToSolveQuiz - leftSecond}
잠깐 보고 성능에 문제가 생길 수도 있겠다고 생각해서 지나쳤었는데, 자세하게 찾아보니까 애니메이션 최적화 방식이네요.
괜찮은 방법 같아요.

2023-07-24 13:09 UTC, Forourhappy commented
> 포 고생하셨어요! 제가 실행을 안해봐서 어떻게 끊기는지는 모르겠으나, 아래 링크처럼 프로그래스 바에 애니메이션을 추가해주면 스무스하게 동작할 수 있을거같아요! https://codepen.io/evawythien/pen/jegRxN

애니메이션으로 해결봐야 하는 거면 위에서 루키가 말한대로 rAF를 이용하는 편이 좋을 것 같군요.

2023-07-24 14:11 UTC, RookieAND commented on src/components/pages/QuizPlay/QuizPlay.style.ts
> +      border: 10px solid ${colors.white};
아 그럴 수 있겠네요. 흠.. 이 부분도 좀 논의해봐야 할듯 싶네요

2023-07-24 15:11 UTC, shinpanda approved these changes

2023-07-29 12:24 UTC, Forourhappy commented
추가 작업을 완료했습니다.

## 추가사항
- timer를 rAF(requestAnimationFrame)을 이용한 로직으로 수정
- color 코드 추가
- merge 후, presetCard.style.tsx를 ts 파일로 변환(@uaej 제가 잘 수정했는지 확인해 주시면 감사하겠습니다.)

2023-07-30 09:32 UTC, uaej approved these changes
확인이 늦어서 죄송합니다!!

2023-07-30 09:32 UTC, uaej commented on src/styles/colors.ts
> +  lightGrey: '#d9d9d9',
#뒤에 대문자로 형식 맞춰주면 좋을거같아요!

2023-07-30 09:32 UTC, uaej commented on src/components/main/PresetCard/PresetCard.style.tsx
이 부분 확인했습니다! ts파일로 바꾸는게 맞습니다. 수정 감사합니다!

2023-07-31 10:11 UTC, merged