[INT-45] 퀴즈 생성페이지(CreateQuiz) 구조 변경
NaYeongSeokGame/ImNayeoungSeokToo-client pull request #46
Opened 2023-07-24 11:13 UTC by uaej

## Jira Issue 번호
#45

## 작업 내용
- 퀴즈 생성 페이지 및 입력 모달 디자인 퍼블리싱
- 해시태그, 퀴즈 비공개 입력 필드 추가

## 추가 전달드릴 내용
- 사진 입력받는 걸 페이지로 바꿀까 하다가 기존에 있는 모달을 수정하는 방식으로 구현했는데, 더 좋은 방식이 있다면 말씀해주세요. 
- hastag 서버에 전송하는 부분은 일단 주석처리 해놓았습니다. 

## Checklist

- [ ] Code Review 요청
- [ ] PR 제목 commit convention에 맞는지 확인
- [ ] Label 설정
- [ ] Jira 코드 리뷰 상태로 변경

2023-07-25 04:22 UTC, RookieAND requested changes
고생하셨습니다 메이.
전반적으로 prettier를 적용하지 않은 점이 몇 가지 보이는데, 작업한 코드에 대해서는 포맷팅을 선행해주시면 감사하겠습니다.

2023-07-25 04:22 UTC, RookieAND commented on src/components/main/AddQuizModal/AddQuizModal.style.ts
> +      padding: 0.625rem 0.91rem;
단위가 0.125 단위로 떨어지지 않거나 하는 친구들은 그냥 개발하는 과정에서 강제하는 것도 고려하면 좋을 거 같네요.

2023-07-25 04:22 UTC, RookieAND commented on src/components/main/AddQuizModal/AddQuizModal.tsx
> +  useEffect(() => {
새로 생성하는 경우에는 진입 시 파일 업로드 창이 표시되어야 하는 이유가 있을까요?

2023-07-25 04:22 UTC, RookieAND commented on src/components/main/HastagInput/HashtagInput.tsx
> +  const hashtagRemove=(index: number)=>{
이런 부분도 prettier를 돌려서 한번 씩 코드 포맷팅을 해주면 더 좋을 거 같아요.

2023-07-25 06:56 UTC, uaej commented on src/components/main/AddQuizModal/AddQuizModal.tsx
> +  useEffect(() => {
피그마에 버튼 문구가 '이미지 재선택' 이어서 처음 진입할때는 자동으로 띄워주는게 맞다고 생각했어요!

2023-07-25 07:11 UTC, uaej commented on src/components/main/AddQuizModal/AddQuizModal.style.ts
> +      padding: 0.625rem 0.91rem;
피그마 그대로 붙여넣기 한 거일텐데 앞으로는 그렇게 작업하겠습니다!

2023-07-25 09:17 UTC, Forourhappy reviewed
기능 많은 페이지 작업하시느라 수고 정말 많으셨습니다!

2023-07-25 15:52 UTC, RookieAND requested changes
조금 더 수정했으면 하는 사항을 추가로 기술하였습니다.

2023-07-25 15:52 UTC, RookieAND commented on src/components/main/CreateQuizImageView/CreateQuizImage.style.ts
> +  ${({ theme, image }) => {
사용하지 않는 매개변수의 경우 _ (언더바) 로 표기해서 첫번째 매개변수는 사용하지 않음을 나타내도 좋아 보여요

2023-07-25 15:52 UTC, RookieAND commented on src/components/main/CreateQuizImageView/CreateQuizImage.style.ts
> +  ${({ theme }) => {
theme을 사용하지 않는다면 그냥 template literal로 쓰는 건 어떤가요?

2023-07-25 15:52 UTC, RookieAND commented on src/components/main/HastagInput/HashtagInput.tsx
> +    hashtag.splice(index, 1);
기존의 배열을 수정해서 spread로 넣는 방법도 있지만 filter를 사용해서 한줄로 축약이 가능해보여요.

```ts
setHashtag(hashtag.filter((_, i) => i !== index))
```

2023-07-27 06:03 UTC, uaej commented on src/components/main/HastagInput/HashtagInput.tsx
> +    hashtag.splice(index, 1);
이거 좋네요!

2023-07-30 07:32 UTC, merged